---
sudo: required
dist: trusty
language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libexpat1-dev
      - zlib1g-dev
      - libxml2-dev
      - libbz2-dev
      - libpq-dev
      - libgeos-c1
      - libgeos++-dev
      - libproj-dev
      - postgresql-server-dev-9.6
      - postgresql-9.6-postgis-2.3
      - postgresql-contrib-9.6
      - apache2
      - php5
      - php5-pgsql
      - php5-intl
      - php-pear
      - python3-dev
      - python3-pip
      - python3-psycopg2
      - php5-cgi
git:
  depth: 1
env:
  - TEST_SUITE=tests
  - TEST_SUITE=monaco
install:
  - vagrant/install-on-travis-ci.sh
before_script:
  - psql -U postgres -c "create extension postgis"
script:
  - cd $TRAVIS_BUILD_DIR/
  - if [[ $TEST_SUITE == "tests" ]]; then phpcs --report-width=120 . ; fi
  - cd $TRAVIS_BUILD_DIR/test/php
  - if [[ $TEST_SUITE == "tests" ]]; then phpunit ./ ; fi
  - cd $TRAVIS_BUILD_DIR/test/bdd
  - # behave --format=progress3 api
  - if [[ $TEST_SUITE == "tests" ]]; then behave -DREMOVE_TEMPLATE=1 --format=progress3 db ; fi
  - if [[ $TEST_SUITE == "tests" ]]; then behave --format=progress3 osm2pgsql ; fi
  - cd $TRAVIS_BUILD_DIR/build
  - if [[ $TEST_SUITE == "monaco" ]]; then wget --no-verbose --output-document=../data/monaco.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf; fi
  - if [[ $TEST_SUITE == "monaco" ]]; then /usr/bin/env php ./utils/setup.php --osm-file ../data/monaco.osm.pbf --osm2pgsql-cache 1000 --all 2>&1 | grep -v 'ETA (seconds)'; fi
  - if [[ $TEST_SUITE == "monaco" ]]; then /usr/bin/env php ./utils/specialphrases.php --wiki-import | psql -d test_api_nominatim >/dev/null; fi
notifications:
  email: false
